[package]
name = "garage_opener"
version = "0.1.0"
authors = ["jdollar <dollarhidejoel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.2"
quicli = "0.4.0"
structopt = "0.2"

